# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-12-07 09:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.FloatField(verbose_name='Price per unit')),
                ('expiry_date', models.DateField()),
                ('company', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
