# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-12-07 09:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0002_medicine'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicine',
            name='medical',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='medical.Medical'),
        ),
    ]
